### ISSUE TITLE
Stability/prod

### ISSUE THREAD

**Issue by mpoiriert** [JCID/JcidLocoBundle#1]
I am currently looking to use https://localise.biz/ as our translation manager for our project (one part of it is symfony).

I was wondering if you still use this and is it stable ? Do you recommend https://localise.biz/ ? What would be the effort to push data to it ?

Thanks !

**Comment by cafferata** [comment]
Hi Martin, Thank you for asking! We, as JCID, are very satisfied with Localize! And Yes, we use it in production of our latests developed applications. The developer behind Localize is open for feedback. When there is an bug, the developer will resolved as soon as possible. We contacted several times in the past, and always got quick response back. Why we would recommend it? We give our clients the possibility to change their own texts, by giving them an editor account/right. When we do a new deployment/release there texts will be taken from Localise back to the project. This saves us time, and customers can have self control over texts. Everybody happy!
